// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file ping.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ping.proto.
 */
export const file_ping: GenFile = /*@__PURE__*/
  fileDesc("CgpwaW5nLnByb3RvEgJwYiINCgtQaW5nUmVxdWVzdCIhCgxQaW5nUmVzcG9uc2USEQoJdGltZXN0YW1wGAEgASgDMjgKC1BpbmdTZXJ2aWNlEikKBFBpbmcSDy5wYi5QaW5nUmVxdWVzdBoQLnBiLlBpbmdSZXNwb25zZUIqWihnaXRodWIuY29tL2ZpbGFtZW50LWxhYnMvcHJvdG8vZ2VuL2dvL3BiYgZwcm90bzM");

/**
 * @generated from message pb.PingRequest
 */
export type PingRequest = Message<"pb.PingRequest"> & {
};

/**
 * Describes the message pb.PingRequest.
 * Use `create(PingRequestSchema)` to create a new message.
 */
export const PingRequestSchema: GenMessage<PingRequest> = /*@__PURE__*/
  messageDesc(file_ping, 0);

/**
 * @generated from message pb.PingResponse
 */
export type PingResponse = Message<"pb.PingResponse"> & {
  /**
   * @generated from field: int64 timestamp = 1;
   */
  timestamp: bigint;
};

/**
 * Describes the message pb.PingResponse.
 * Use `create(PingResponseSchema)` to create a new message.
 */
export const PingResponseSchema: GenMessage<PingResponse> = /*@__PURE__*/
  messageDesc(file_ping, 1);

/**
 * @generated from service pb.PingService
 */
export const PingService: GenService<{
  /**
   * @generated from rpc pb.PingService.Ping
   */
  ping: {
    methodKind: "unary";
    input: typeof PingRequestSchema;
    output: typeof PingResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_ping, 0);

