// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file transaction.proto (package pb, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetTransactionRequest, GetTransactionResponse, ListTransactionsRequest, ListTransactionsResponse, SendTransactionRequest, SendTransactionResponse, StreamWalletTransactionsRequest, StreamWalletTransactionsResponse } from "./transaction_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service pb.TransactionService
 */
export const TransactionService = {
  typeName: "pb.TransactionService",
  methods: {
    /**
     * Initiate a new transaction (e.g., broadcasting to the network)
     *
     * @generated from rpc pb.TransactionService.SendTransaction
     */
    sendTransaction: {
      name: "SendTransaction",
      I: SendTransactionRequest,
      O: SendTransactionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieve details for a specific transaction
     *
     * @generated from rpc pb.TransactionService.GetTransaction
     */
    getTransaction: {
      name: "GetTransaction",
      I: GetTransactionRequest,
      O: GetTransactionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieve a list of transactions, typically for a specific wallet
     *
     * @generated from rpc pb.TransactionService.ListTransactions
     */
    listTransactions: {
      name: "ListTransactions",
      I: ListTransactionsRequest,
      O: ListTransactionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Streams transaction updates from the blockchain in real-time
     *
     * @generated from rpc pb.TransactionService.StreamWalletTransactions
     */
    streamWalletTransactions: {
      name: "StreamWalletTransactions",
      I: StreamWalletTransactionsRequest,
      O: StreamWalletTransactionsResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

