// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file wallet.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file wallet.proto.
 */
export const file_wallet: GenFile = /*@__PURE__*/
  fileDesc("Cgx3YWxsZXQucHJvdG8SAnBiIiUKEEdldFdhbGxldFJlcXVlc3QSEQoJd2FsbGV0X2lkGAEgASgJIvQBChFHZXRXYWxsZXRSZXNwb25zZRIKCgJpZBgBIAEoCRISCgppc19kZWZhdWx0GAIgASgIEhMKC3dhbGxldF9uYW1lGAMgASgJEjcKCWFkZHJlc3NlcxgEIAMoCzIkLnBiLkdldFdhbGxldFJlc3BvbnNlLkFkZHJlc3Nlc0VudHJ5Eg8KB2JhbGFuY2UYBSABKAkSLgoKY3JlYXRlZF9hdBgGIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAaMAoOQWRkcmVzc2VzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASITChFHZXRXYWxsZXRzUmVxdWVzdCJPChJHZXRXYWxsZXRzUmVzcG9uc2USEQoJaXNfbG9ja2VkGAEgASgIEiYKB3dhbGxldHMYAiADKAsyFS5wYi5HZXRXYWxsZXRSZXNwb25zZSJSChNDcmVhdGVXYWxsZXRSZXF1ZXN0EhMKC3dhbGxldF9uYW1lGAEgASgJEhcKCnBhc3NwaHJhc2UYAiABKAlIAIgBAUINCgtfcGFzc3BocmFzZSI9ChRDcmVhdGVXYWxsZXRSZXNwb25zZRIlCgZ3YWxsZXQYASABKAsyFS5wYi5HZXRXYWxsZXRSZXNwb25zZSJUChRSZWNvdmVyV2FsbGV0UmVxdWVzdBITCgt3YWxsZXRfbmFtZRgBIAEoCRISCgpwYXNzcGhyYXNlGAIgASgJEhMKC3NlZWRfcGhyYXNlGAMgASgJIj4KFVJlY292ZXJXYWxsZXRSZXNwb25zZRIlCgZ3YWxsZXQYASABKAsyFS5wYi5HZXRXYWxsZXRSZXNwb25zZSJ8ChNVcGRhdGVXYWxsZXRSZXF1ZXN0EhEKCXdhbGxldF9pZBgBIAEoCRIYCgt3YWxsZXRfbmFtZRgCIAEoCUgAiAEBEhgKC3NldF9kZWZhdWx0GAMgASgISAGIAQFCDgoMX3dhbGxldF9uYW1lQg4KDF9zZXRfZGVmYXVsdCI9ChRVcGRhdGVXYWxsZXRSZXNwb25zZRIlCgZ3YWxsZXQYASABKAsyFS5wYi5HZXRXYWxsZXRSZXNwb25zZSIoChNEZWxldGVXYWxsZXRSZXF1ZXN0EhEKCXdhbGxldF9pZBgBIAEoCSIWChREZWxldGVXYWxsZXRSZXNwb25zZTKVAwoNV2FsbGV0U2VydmljZRI4CglHZXRXYWxsZXQSFC5wYi5HZXRXYWxsZXRSZXF1ZXN0GhUucGIuR2V0V2FsbGV0UmVzcG9uc2USOwoKR2V0V2FsbGV0cxIVLnBiLkdldFdhbGxldHNSZXF1ZXN0GhYucGIuR2V0V2FsbGV0c1Jlc3BvbnNlEkEKDENyZWF0ZVdhbGxldBIXLnBiLkNyZWF0ZVdhbGxldFJlcXVlc3QaGC5wYi5DcmVhdGVXYWxsZXRSZXNwb25zZRJECg1SZWNvdmVyV2FsbGV0EhgucGIuUmVjb3ZlcldhbGxldFJlcXVlc3QaGS5wYi5SZWNvdmVyV2FsbGV0UmVzcG9uc2USQQoMVXBkYXRlV2FsbGV0EhcucGIuVXBkYXRlV2FsbGV0UmVxdWVzdBoYLnBiLlVwZGF0ZVdhbGxldFJlc3BvbnNlEkEKDERlbGV0ZVdhbGxldBIXLnBiLkRlbGV0ZVdhbGxldFJlcXVlc3QaGC5wYi5EZWxldGVXYWxsZXRSZXNwb25zZUIqWihnaXRodWIuY29tL2ZpbGFtZW50LWxhYnMvcHJvdG8vZ2VuL2dvL3BiYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * Request to retrieve a single, specific wallet by its unique identifier.
 *
 * @generated from message pb.GetWalletRequest
 */
export type GetWalletRequest = Message<"pb.GetWalletRequest"> & {
  /**
   * The unique ID of the wallet to retrieve.
   *
   * @generated from field: string wallet_id = 1;
   */
  walletId: string;
};

/**
 * Describes the message pb.GetWalletRequest.
 * Use `create(GetWalletRequestSchema)` to create a new message.
 */
export const GetWalletRequestSchema: GenMessage<GetWalletRequest> = /*@__PURE__*/
  messageDesc(file_wallet, 0);

/**
 * Response containing the detailed information about a single wallet.
 *
 * @generated from message pb.GetWalletResponse
 */
export type GetWalletResponse = Message<"pb.GetWalletResponse"> & {
  /**
   * The unique ID of the wallet.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Indicates if this is the user's primary wallet.
   *
   * @generated from field: bool is_default = 2;
   */
  isDefault: boolean;

  /**
   * User-defined name for the wallet (e.g., "Savings", "Trading").
   *
   * @generated from field: string wallet_name = 3;
   */
  walletName: string;

  /**
   * Map of address type (f1, f4, 0x) to its address (value).
   *
   * @generated from field: map<string, string> addresses = 4;
   */
  addresses: { [key: string]: string };

  /**
   * Use a string for financial amounts to prevent floating-point inaccuracies.
   *
   * @generated from field: string balance = 5;
   */
  balance: string;

  /**
   * Timestamp when the wallet was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp;
};

/**
 * Describes the message pb.GetWalletResponse.
 * Use `create(GetWalletResponseSchema)` to create a new message.
 */
export const GetWalletResponseSchema: GenMessage<GetWalletResponse> = /*@__PURE__*/
  messageDesc(file_wallet, 1);

/**
 * Request to retrieve all wallets associated with the authenticated user.
 *
 * @generated from message pb.GetWalletsRequest
 */
export type GetWalletsRequest = Message<"pb.GetWalletsRequest"> & {
};

/**
 * Describes the message pb.GetWalletsRequest.
 * Use `create(GetWalletsRequestSchema)` to create a new message.
 */
export const GetWalletsRequestSchema: GenMessage<GetWalletsRequest> = /*@__PURE__*/
  messageDesc(file_wallet, 2);

/**
 * Response containing a list of all wallets and the account lock status.
 *
 * @generated from message pb.GetWalletsResponse
 */
export type GetWalletsResponse = Message<"pb.GetWalletsResponse"> & {
  /**
   * Indicates if the user's wallet system is locked (requires passphrase).
   *
   * @generated from field: bool is_locked = 1;
   */
  isLocked: boolean;

  /**
   * The list of all retrieved wallets.
   *
   * @generated from field: repeated pb.GetWalletResponse wallets = 2;
   */
  wallets: GetWalletResponse[];
};

/**
 * Describes the message pb.GetWalletsResponse.
 * Use `create(GetWalletsResponseSchema)` to create a new message.
 */
export const GetWalletsResponseSchema: GenMessage<GetWalletsResponse> = /*@__PURE__*/
  messageDesc(file_wallet, 3);

/**
 * Request to create a new wallet.
 *
 * @generated from message pb.CreateWalletRequest
 */
export type CreateWalletRequest = Message<"pb.CreateWalletRequest"> & {
  /**
   * The initial name for the new wallet.
   *
   * @generated from field: string wallet_name = 1;
   */
  walletName: string;

  /**
   * Optional passphrase for initial encryption/unlock.
   *
   * @generated from field: optional string passphrase = 2;
   */
  passphrase?: string;
};

/**
 * Describes the message pb.CreateWalletRequest.
 * Use `create(CreateWalletRequestSchema)` to create a new message.
 */
export const CreateWalletRequestSchema: GenMessage<CreateWalletRequest> = /*@__PURE__*/
  messageDesc(file_wallet, 4);

/**
 * Response returning the details of the newly created wallet.
 *
 * @generated from message pb.CreateWalletResponse
 */
export type CreateWalletResponse = Message<"pb.CreateWalletResponse"> & {
  /**
   * @generated from field: pb.GetWalletResponse wallet = 1;
   */
  wallet?: GetWalletResponse;
};

/**
 * Describes the message pb.CreateWalletResponse.
 * Use `create(CreateWalletResponseSchema)` to create a new message.
 */
export const CreateWalletResponseSchema: GenMessage<CreateWalletResponse> = /*@__PURE__*/
  messageDesc(file_wallet, 5);

/**
 * @generated from message pb.RecoverWalletRequest
 */
export type RecoverWalletRequest = Message<"pb.RecoverWalletRequest"> & {
  /**
   * @generated from field: string wallet_name = 1;
   */
  walletName: string;

  /**
   * @generated from field: string passphrase = 2;
   */
  passphrase: string;

  /**
   * @generated from field: string seed_phrase = 3;
   */
  seedPhrase: string;
};

/**
 * Describes the message pb.RecoverWalletRequest.
 * Use `create(RecoverWalletRequestSchema)` to create a new message.
 */
export const RecoverWalletRequestSchema: GenMessage<RecoverWalletRequest> = /*@__PURE__*/
  messageDesc(file_wallet, 6);

/**
 * @generated from message pb.RecoverWalletResponse
 */
export type RecoverWalletResponse = Message<"pb.RecoverWalletResponse"> & {
  /**
   * @generated from field: pb.GetWalletResponse wallet = 1;
   */
  wallet?: GetWalletResponse;
};

/**
 * Describes the message pb.RecoverWalletResponse.
 * Use `create(RecoverWalletResponseSchema)` to create a new message.
 */
export const RecoverWalletResponseSchema: GenMessage<RecoverWalletResponse> = /*@__PURE__*/
  messageDesc(file_wallet, 7);

/**
 * Request to update metadata for an existing wallet.
 *
 * @generated from message pb.UpdateWalletRequest
 */
export type UpdateWalletRequest = Message<"pb.UpdateWalletRequest"> & {
  /**
   * The ID of the wallet to modify.
   *
   * @generated from field: string wallet_id = 1;
   */
  walletId: string;

  /**
   * Optional: New name for the wallet.
   *
   * @generated from field: optional string wallet_name = 2;
   */
  walletName?: string;

  /**
   * Optional: Set this wallet as the user's new default.
   *
   * @generated from field: optional bool set_default = 3;
   */
  setDefault?: boolean;
};

/**
 * Describes the message pb.UpdateWalletRequest.
 * Use `create(UpdateWalletRequestSchema)` to create a new message.
 */
export const UpdateWalletRequestSchema: GenMessage<UpdateWalletRequest> = /*@__PURE__*/
  messageDesc(file_wallet, 8);

/**
 * Response returning the updated wallet details.
 *
 * @generated from message pb.UpdateWalletResponse
 */
export type UpdateWalletResponse = Message<"pb.UpdateWalletResponse"> & {
  /**
   * @generated from field: pb.GetWalletResponse wallet = 1;
   */
  wallet?: GetWalletResponse;
};

/**
 * Describes the message pb.UpdateWalletResponse.
 * Use `create(UpdateWalletResponseSchema)` to create a new message.
 */
export const UpdateWalletResponseSchema: GenMessage<UpdateWalletResponse> = /*@__PURE__*/
  messageDesc(file_wallet, 9);

/**
 * Request to delete or archive a wallet.
 *
 * @generated from message pb.DeleteWalletRequest
 */
export type DeleteWalletRequest = Message<"pb.DeleteWalletRequest"> & {
  /**
   * The ID of the wallet to delete.
   *
   * @generated from field: string wallet_id = 1;
   */
  walletId: string;
};

/**
 * Describes the message pb.DeleteWalletRequest.
 * Use `create(DeleteWalletRequestSchema)` to create a new message.
 */
export const DeleteWalletRequestSchema: GenMessage<DeleteWalletRequest> = /*@__PURE__*/
  messageDesc(file_wallet, 10);

/**
 * Response for deletion. Empty response signals success.
 *
 * @generated from message pb.DeleteWalletResponse
 */
export type DeleteWalletResponse = Message<"pb.DeleteWalletResponse"> & {
};

/**
 * Describes the message pb.DeleteWalletResponse.
 * Use `create(DeleteWalletResponseSchema)` to create a new message.
 */
export const DeleteWalletResponseSchema: GenMessage<DeleteWalletResponse> = /*@__PURE__*/
  messageDesc(file_wallet, 11);

/**
 * The primary service interface for managing the user's wallet portfolio.
 *
 * @generated from service pb.WalletService
 */
export const WalletService: GenService<{
  /**
   * Retrieves the detailed information for a single wallet.
   *
   * @generated from rpc pb.WalletService.GetWallet
   */
  getWallet: {
    methodKind: "unary";
    input: typeof GetWalletRequestSchema;
    output: typeof GetWalletResponseSchema;
  },
  /**
   * Retrieves a list of all wallets belonging to the user.
   *
   * @generated from rpc pb.WalletService.GetWallets
   */
  getWallets: {
    methodKind: "unary";
    input: typeof GetWalletsRequestSchema;
    output: typeof GetWalletsResponseSchema;
  },
  /**
   * Creates a new cryptographic wallet and saves its metadata.
   *
   * @generated from rpc pb.WalletService.CreateWallet
   */
  createWallet: {
    methodKind: "unary";
    input: typeof CreateWalletRequestSchema;
    output: typeof CreateWalletResponseSchema;
  },
  /**
   * @generated from rpc pb.WalletService.RecoverWallet
   */
  recoverWallet: {
    methodKind: "unary";
    input: typeof RecoverWalletRequestSchema;
    output: typeof RecoverWalletResponseSchema;
  },
  /**
   * Updates mutable metadata associated with a wallet (name, default status).
   *
   * @generated from rpc pb.WalletService.UpdateWallet
   */
  updateWallet: {
    methodKind: "unary";
    input: typeof UpdateWalletRequestSchema;
    output: typeof UpdateWalletResponseSchema;
  },
  /**
   * Permanently deletes or archives a wallet record.
   *
   * @generated from rpc pb.WalletService.DeleteWallet
   */
  deleteWallet: {
    methodKind: "unary";
    input: typeof DeleteWalletRequestSchema;
    output: typeof DeleteWalletResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_wallet, 0);

